In [1]:
import numpy as np
import math
import scipy.io
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnnotationBbox, OffsetImage

In [3]:
mat = scipy.io.loadmat('D:/Users/Ziqiu/OneDrive/Documents/University Docs/Stat441/Stat441 A1/0_1_2.mat')
X = mat['X']
Xt = X.transpose()

In [4]:
label0 = Xt[0:100,:]
label1 = Xt[100:200,:]
label2 = Xt[200:300,:]
u0 = label0.mean(axis=0).reshape(64,1)
u1 = label1.mean(axis=0).reshape(64,1)
u2 = label2.mean(axis=0).reshape(64,1)

s1 = np.cov(label0.T)
s2 = np.cov(label1.T)
s3 = np.cov(label2.T)
s = (s1 + s2 + s3)/3
Sinv=(np.linalg.inv(s))
print(u1.shape)
print(s2)
print(s3)


(64, 1)
[[0.00400682 0.00906338 0.00518106 ... 0.00561793 0.00765606 0.00354949]
 [0.00906338 0.0272553  0.02398712 ... 0.02451793 0.02409646 0.00777778]
 [0.00518106 0.02398712 0.03081635 ... 0.03268151 0.02537901 0.00529188]
 ...
 [0.00561793 0.02451793 0.03268151 ... 0.0504507  0.0344982  0.00651107]
 [0.00765606 0.02409646 0.02537901 ... 0.0344982  0.03254986 0.00982473]
 [0.00354949 0.00777778 0.00529188 ... 0.00651107 0.00982473 0.00492994]]
[[ 0.01364173  0.02181471  0.01519609 ...  0.00257858 -0.00097509
   0.00014663]
 [ 0.02181471  0.05727935  0.05120695 ...  0.00237176  0.00241228
   0.00433046]
 [ 0.01519609  0.05120695  0.07945555 ...  0.00756886  0.01445372
   0.01383705]
 ...
 [ 0.00257858  0.00237176  0.00756886 ...  0.0666688   0.04010499
   0.01075499]
 [-0.00097509  0.00241228  0.01445372 ...  0.04010499  0.06881895
   0.03457552]
 [ 0.00014663  0.00433046  0.01383705 ...  0.01075499  0.03457552
   0.03581996]]


In [5]:
def argmaxd(x):
    def d0(x):
        return x.T @ Sinv @ u0 - 0.5 * u0.T @ Sinv @ u0 + math.log(1/3)
    def d1(x):
        return x.T @ Sinv @ u1 - 0.5 * u1.T @ Sinv @ u1 + math.log(1/3)
    def d2(x):
        return x.T @ Sinv @ u2 - 0.5 * u2.T @ Sinv @ u2 + math.log(1/3)
    if max(d0(x),d1(x),d2(x)) == d0(x):
        return 0
    if max(d0(x),d1(x),d2(x)) == d1(x):
        return 1
    return 2

def classifier(x):
    return [argmaxd(i) for i in x]

In [6]:
classifier(Xt)
print(np.bincount(classifier(Xt[0:100,:])))
print(np.bincount(classifier(Xt[100:200,:])))
print(np.bincount(classifier(Xt[200:300,:])))

[98  2]
[  0 100]
[  0   0 100]
